# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- bundle install
- bundle exec pod install --project-directory=Example
env:
  matrix:
    - TASK=carthage
    - TASK=xcodebuild
    - TASK=podlint
script:
- bundle exec rake ci:$TASK
